### ISSUE TITLE
Max limit of MOV file is 512MB

### ISSUE THREAD

**Issue by marknorrapscm** [simalexan/s3-lambda-ffmpeg-mov-to-mp4-s3#4]
This is a question more than an issue, but looking at the code it appears that the MOV file from S3 is being written to the `/tmp/` directory in the Lambda.

The `/tmp/` directory has a max file size of 512MB, so anything exceeding this will cause the app to crash.

Can you confirm this to be true? A workaround would be to stream and pipe the file into ffmpeg but this is something I could not get to work within Lambda functions.

**Comment by San-Jeevan** [comment]
@marknorrapscm  try https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/
change the line
`workdir = os.tmpdir(),`
to your mount drive

you are no more limited to 512 MB.

**Comment by marknorrapscm** [comment]
Thanks @San-Jeevan, I wasn't aware that mounting an EFS was possible. Looks like it has only been out for a few months.

This repo doesn't have it implemented though - I would have to fork it - but I can use it in my own implementation if needed.
